// KQL script
// Use management commands in this script to configure your database items, such as tables, functions, materialized views, and more.


.create-merge table BronzeIoTData (messageId:long, deviceId:string, temperature:dynamic, humidity:dynamic, EventProcessedUtcTime:datetime, PartitionId:long, EventEnqueuedUtcTime:datetime, IoTHub:dynamic) 
.create-merge table GoldIoT (PartitionId:long, COUNT_All:dynamic, Window_End_Time:datetime) 
