// KQL script
// Use management commands in this script to configure your database items, such as tables, functions, materialized views, and more.


.create-merge table iotrawdata (messageId:long, deviceId:string, temperature:real, humidity:real, EventProcessedUtcTime:datetime, PartitionId:long, EventEnqueuedUtcTime:datetime, IoTHub:dynamic) 
.create-merge table Temp30mais (current_time:datetime, messageId:long, deviceId:string, temperature:real, humidity:real, EventProcessedUtcTime:datetime, PartitionId:long, EventEnqueuedUtcTime:datetime, IoTHub:dynamic) 
