// KQL script
// Use management commands in this script to configure your database items, such as tables, functions, materialized views, and more.


.create-merge table RaspBTable (messageId:long, deviceId:string, temperature:real, humidity:real, EventProcessedUtcTime:datetime, PartitionId:long, EventEnqueuedUtcTime:datetime, IoTHub:dynamic) 
.create-merge table Temp24 (messageId:long, deviceId:string, temperature:real, humidity:real, EventProcessedUtcTime:datetime, PartitionId:long, EventEnqueuedUtcTime:datetime, IoTHub:dynamic) 
